import { Profile } from "@/types";

const summary = "You share practical home-life preferences. Start a conversation to compare routines, expectations and boundaries.";

export const demoProfiles: Profile[] = [
  { id: "riya", name: "Riya", age: 23, gender: "Woman", occupation: "Software Engineer", organization: "Orbit Labs", city: "Bengaluru", preferredCity: "Bengaluru", budgetMin: 12000, budgetMax: 18000, bio: "Cozy nights, good coffee and meaningful conversations. Looking for a calm, respectful roommate.", verified: true, compatibility: { overall: 92, lifestyle: 94, budget: 88, location: 100, summary, common: ["Vegetarian", "Clean living", "Homebody", "Coffee"] }, lifestyle: { food: "Vegetarian", sleep: "Early sleeper", cleanliness: 9, social: "Ambivert", party: "Homebody", smoking: false, drinking: false, cooking: "Love cooking", guests: "Sometimes", music: "Moderate", workStyle: "Hybrid", pets: "Love", languages: ["English", "Hindi"], privacy: 8, sharingFood: true, borrowing: true, noiseTolerance: 4 } },
  { id: "aanya", name: "Aanya", age: 22, gender: "Woman", occupation: "Graduate Student", organization: "Delhi University", city: "Delhi", preferredCity: "Delhi", budgetMin: 9000, budgetMax: 14000, bio: "Reader, yoga beginner, and fan of calm evenings. I keep shared spaces warm and tidy.", compatibility: { overall: 87, lifestyle: 91, budget: 84, location: 86, summary, common: ["Early riser", "No smoking", "Occasional cooking"] }, lifestyle: { food: "Vegan", sleep: "Early sleeper", cleanliness: 8, social: "Introvert", party: "Homebody", smoking: false, drinking: false, cooking: "Can cook", guests: "Never", music: "Quiet", workStyle: "Student", pets: "Okay", languages: ["English", "Hindi"], privacy: 9, sharingFood: true, borrowing: false, noiseTolerance: 3 } },
  { id: "arjun", name: "Arjun", age: 25, gender: "Man", occupation: "Product Designer", organization: "Pixel Works", city: "Pune", preferredCity: "Pune", budgetMin: 14000, budgetMax: 21000, bio: "Designer, weekend cyclist and a reliable cook. I enjoy a social but peaceful home.", verified: true, compatibility: { overall: 89, lifestyle: 90, budget: 86, location: 92, summary, common: ["Hybrid work", "Can cook", "Pet friendly", "Tidy"] }, lifestyle: { food: "Non-Vegetarian", sleep: "Night owl", cleanliness: 8, social: "Ambivert", party: "Occasionally party", smoking: false, drinking: true, cooking: "Can cook", guests: "Sometimes", music: "Moderate", workStyle: "Hybrid", pets: "Love", languages: ["English", "Hindi", "Marathi"], privacy: 7, sharingFood: true, borrowing: true, noiseTolerance: 6 } },
  { id: "kabir", name: "Kabir", age: 26, gender: "Man", occupation: "Data Analyst", organization: "Northstar", city: "Hyderabad", preferredCity: "Hyderabad", budgetMin: 13000, budgetMax: 19000, bio: "WFH analyst who likes cricket, playlists and keeping the kitchen organised.", compatibility: { overall: 84, lifestyle: 85, budget: 88, location: 78, summary, common: ["WFH", "No smoking", "Moderate music", "Organised"] }, lifestyle: { food: "Non-Vegetarian", sleep: "Early sleeper", cleanliness: 9, social: "Introvert", party: "Homebody", smoking: false, drinking: false, cooking: "Love cooking", guests: "Sometimes", music: "Moderate", workStyle: "WFH", pets: "Okay", languages: ["English", "Hindi", "Telugu"], privacy: 8, sharingFood: true, borrowing: false, noiseTolerance: 5 } },
  { id: "meera", name: "Meera", age: 24, gender: "Woman", occupation: "Marketing Associate", organization: "Mint Creative", city: "Mumbai", preferredCity: "Mumbai", budgetMin: 18000, budgetMax: 26000, bio: "Friendly marketer, plant parent and occasional host. I value direct, kind communication.", compatibility: { overall: 86, lifestyle: 89, budget: 80, location: 88, summary, common: ["Plant lover", "Ambivert", "Clean living", "Guests sometimes"] }, lifestyle: { food: "Vegetarian", sleep: "Night owl", cleanliness: 8, social: "Extrovert", party: "Occasionally party", smoking: false, drinking: true, cooking: "Can cook", guests: "Sometimes", music: "Moderate", workStyle: "Working professional", pets: "Love", languages: ["English", "Hindi", "Gujarati"], privacy: 7, sharingFood: true, borrowing: true, noiseTolerance: 6 } },
  { id: "dev", name: "Dev", age: 27, gender: "Man", occupation: "Consultant", organization: "Civic Partners", city: "Gurugram", preferredCity: "Gurugram", budgetMin: 16000, budgetMax: 24000, bio: "Consultant with an early schedule. I prefer a quiet, clean flat and clear shared responsibilities.", verified: true, compatibility: { overall: 82, lifestyle: 84, budget: 83, location: 79, summary, common: ["Early sleeper", "Quiet home", "No smoking", "Professional"] }, lifestyle: { food: "Vegetarian", sleep: "Early sleeper", cleanliness: 9, social: "Ambivert", party: "Homebody", smoking: false, drinking: false, cooking: "Cannot cook", guests: "Never", music: "Quiet", workStyle: "Working professional", pets: "Not comfortable", languages: ["English", "Hindi"], privacy: 9, sharingFood: false, borrowing: false, noiseTolerance: 3 } },
  { id: "isha", name: "Isha", age: 23, gender: "Woman", occupation: "UX Researcher", organization: "Blue Door", city: "Bengaluru", preferredCity: "Bengaluru", budgetMin: 15000, budgetMax: 22000, bio: "Curious researcher, café explorer and respectful flatmate who enjoys relaxed evenings.", compatibility: { overall: 90, lifestyle: 92, budget: 85, location: 96, summary, common: ["Vegetarian", "Hybrid work", "Ambivert", "Calm evenings"] }, lifestyle: { food: "Vegetarian", sleep: "Night owl", cleanliness: 8, social: "Ambivert", party: "Occasionally party", smoking: false, drinking: false, cooking: "Can cook", guests: "Sometimes", music: "Moderate", workStyle: "Hybrid", pets: "Okay", languages: ["English", "Hindi", "Kannada"], privacy: 8, sharingFood: true, borrowing: true, noiseTolerance: 5 } },
  { id: "rohan", name: "Rohan", age: 24, gender: "Man", occupation: "Medical Intern", organization: "City Hospital", city: "Indore", preferredCity: "Indore", budgetMin: 10000, budgetMax: 16000, bio: "Medical intern with changing shifts. Easy-going, considerate and serious about keeping common areas clean.", compatibility: { overall: 80, lifestyle: 82, budget: 86, location: 70, summary, common: ["Clean living", "No smoking", "Easy-going", "Can cook"] }, lifestyle: { food: "Non-Vegetarian", sleep: "Night owl", cleanliness: 8, social: "Ambivert", party: "Homebody", smoking: false, drinking: false, cooking: "Can cook", guests: "Sometimes", music: "Quiet", workStyle: "Working professional", pets: "Okay", languages: ["English", "Hindi"], privacy: 7, sharingFood: true, borrowing: false, noiseTolerance: 5 } },
];
