import AsyncStorage from "@react-native-async-storage/async-storage";
import * as SecureStore from "expo-secure-store";
import { createContext, PropsWithChildren, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { demoProfiles } from "@/theme/demo";
import { Lifestyle, Profile } from "@/types";
import { addBookmark, discover, getBookmarks, removeBookmark, saveProfile, swipeProfile } from "@/services/profiles";
import { registerPush } from "@/services/notifications";
import { defaultPreferences, scoreDemoProfile } from "@/services/compatibility";

type State={ready:boolean;onboarded:boolean;authenticated:boolean;profiles:Profile[];index:number;bookmarks:string[];likes:string[];preferences:Partial<Lifestyle>;loading:boolean;error:string|null;completeOnboarding:()=>void;setAuthenticated:(value:boolean)=>void;refresh:(answers?:Partial<Lifestyle>)=>Promise<void>;swipe:(liked:boolean)=>Promise<void>;toggleBookmark:(id:string)=>Promise<void>;savePreferences:(values:Partial<Lifestyle>)=>Promise<void>};
const Context=createContext<State|null>(null);
export function AppProvider({children}:PropsWithChildren){
 const[ready,setReady]=useState(false);const[onboarded,setOnboarded]=useState(false);const[authenticated,setAuthenticated]=useState(false);const[preferences,setPreferences]=useState<Partial<Lifestyle>>(defaultPreferences);const[profiles,setProfiles]=useState<Profile[]>(demoProfiles.map(profile=>scoreDemoProfile(profile,defaultPreferences)));const[index,setIndex]=useState(0);const[bookmarks,setBookmarks]=useState<string[]>([]);const[likes,setLikes]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);
 const buildDeck=useCallback((real:Profile[],answers:Partial<Lifestyle>)=>{const names=new Set(real.map(profile=>profile.name.toLowerCase()));const fillers=demoProfiles.filter(profile=>!names.has(profile.name.toLowerCase())).map(profile=>scoreDemoProfile(profile,answers));return[...real,...fillers].slice(0,8)},[]);
 const refresh=useCallback(async(answers:Partial<Lifestyle>=preferences)=>{setLoading(true);setError(null);try{const[p,b]=await Promise.all([discover(),getBookmarks()]);setProfiles(buildDeck(p,answers));setBookmarks(current=>[...new Set([...current,...b.map(x=>x.id)])]);await registerPush()}catch(e){setError(e instanceof Error?e.message:"Could not refresh StayMate");setProfiles(buildDeck([],answers))}finally{setLoading(false)}},[buildDeck,preferences]);
 useEffect(()=>{Promise.all([AsyncStorage.getItem("onboarded"),AsyncStorage.getItem("staymate_demo_likes"),AsyncStorage.getItem("staymate_demo_bookmarks"),AsyncStorage.getItem("staymate_preferences"),SecureStore.getItemAsync("staymate_token")]).then(([seen,savedLikes,savedBookmarks,savedPreferences,token])=>{const answers=savedPreferences?{...defaultPreferences,...JSON.parse(savedPreferences)}:defaultPreferences;setOnboarded(seen==="true");setLikes(savedLikes?JSON.parse(savedLikes):[]);setBookmarks(savedBookmarks?JSON.parse(savedBookmarks):[]);setPreferences(answers);setProfiles(buildDeck([],answers));setAuthenticated(Boolean(token));setReady(true);if(token)void refresh(answers)})},[buildDeck]);
 const completeOnboarding=()=>{setOnboarded(true);void AsyncStorage.setItem("onboarded","true")};
 const swipe=async(liked:boolean)=>{const profile=profiles[index%profiles.length];if(!profile)return;setIndex(x=>x+1);if(liked)setLikes(current=>{const next=[...new Set([...current,profile.id])];void AsyncStorage.setItem("staymate_demo_likes",JSON.stringify(next));return next});const isDatabaseProfile=/^[a-f\d]{24}$/i.test(profile.id);if(authenticated&&isDatabaseProfile)try{await swipeProfile(profile.id,liked)}catch(e){setError(e instanceof Error?e.message:"Swipe failed")}};
 const toggleBookmark=async(id:string)=>{const exists=bookmarks.includes(id);const next=exists?bookmarks.filter(value=>value!==id):[...bookmarks,id];setBookmarks(next);const isDatabaseProfile=/^[a-f\d]{24}$/i.test(id);if(!isDatabaseProfile){await AsyncStorage.setItem("staymate_demo_bookmarks",JSON.stringify(next.filter(value=>!(/^[a-f\d]{24}$/i.test(value)))));return}if(authenticated)try{await(exists?removeBookmark(id):addBookmark(id))}catch(e){setBookmarks(current=>exists?[...new Set([...current,id])]:current.filter(value=>value!==id));setError(e instanceof Error?e.message:"Bookmark failed")}};
 const savePreferences=async(values:Partial<Lifestyle>)=>{const next={...preferences,...values};setPreferences(next);setProfiles(current=>current.map(profile=>/^[a-f\d]{24}$/i.test(profile.id)?profile:scoreDemoProfile(profile,next)));await AsyncStorage.setItem("staymate_preferences",JSON.stringify(next));if(authenticated)try{await saveProfile({lifestyle:next})}catch(e){setError(e instanceof Error?e.message:"Preferences saved locally but could not sync")}};
 const value=useMemo(()=>({ready,onboarded,authenticated,profiles,index,bookmarks,likes,preferences,loading,error,completeOnboarding,setAuthenticated,refresh,swipe,toggleBookmark,savePreferences}),[ready,onboarded,authenticated,profiles,index,bookmarks,likes,preferences,loading,error,refresh]);return <Context.Provider value={value}>{children}</Context.Provider>
}
export const useApp=()=>{const value=useContext(Context);if(!value)throw new Error("useApp must be inside AppProvider");return value};
